import datetime

MOCK_CAMPAIGNS = [
    {
        "id": "MC001",
        "name": "Mother's Day — Gold Studs Drop",
        "category": "Holiday/Seasonal",
        "channel": "email",
        "send_date": datetime.date(2026, 5, 10),
        "phase": "planning",
        "tags": ["Holiday", "Product Launch"],
        "segment": "All Email Subscribers",
        "audience_est": 52340,
        "subject_line_draft": "",
        "preview_text_draft": "",
        "copy_notes": "",
        "personalization_notes": "First name token in subject; product rec block based on browse history",
        "design_brief": "",
        "revenue_est": 31200,
        "assigned_to": "Maya Chen",
        "brief_status": "Not Started",
        "design_status": "Not Started",
        "qa_status": "Not Started",
        "priority": "High",
        "category_tag": "holiday",
        "next_deadline": datetime.date(2026, 5, 7),
        "next_deadline_label": "Brief due",
        "task_assignments": [],
    },
    {
        "id": "MC002",
        "name": "Mother's Day SMS Reminder",
        "category": "Holiday/Seasonal",
        "channel": "sms",
        "send_date": datetime.date(2026, 5, 9),
        "phase": "decisioning",
        "tags": ["Holiday", "Urgency"],
        "segment": "SMS Subscribers — Engaged 60d",
        "audience_est": 18420,
        "subject_line_draft": "",
        "preview_text_draft": "",
        "copy_notes": "Short urgency message — 160 chars max. Include link to gift guide.",
        "personalization_notes": "First name only",
        "design_brief": "",
        "revenue_est": 12800,
        "assigned_to": "Jordan Park",
        "brief_status": "Not Started",
        "design_status": "Not Started",
        "qa_status": "Not Started",
        "priority": "High",
        "category_tag": "holiday",
        "next_deadline": datetime.date(2026, 5, 6),
        "next_deadline_label": "Audience sign-off",
        "task_assignments": [
            {"task": "Confirm SMS audience segment", "team": "Data", "role": "Input Provider", "note": "", "due": datetime.date(2026, 5, 6)},
        ],
    },
    {
        "id": "MC003",
        "name": "Spring Restock: Opal Collection",
        "category": "Restock",
        "channel": "email",
        "send_date": datetime.date(2026, 5, 15),
        "phase": "generation",
        "tags": ["Restock", "Product"],
        "segment": "Opal Wishlist + Engaged 90d",
        "audience_est": 24100,
        "subject_line_draft": "It's back — the opal stack you've been waiting for",
        "preview_text_draft": "Limited quantities. Shop before it sells out again.",
        "copy_notes": "Lead with scarcity. Highlight top 3 opal SKUs. CTA: Shop Now.",
        "personalization_notes": "Wishlist match block — show the specific opal piece they saved",
        "design_brief": "Clean product-forward layout. 2-column grid of opal pieces.",
        "revenue_est": 18900,
        "assigned_to": "Maya Chen",
        "brief_status": "In Review",
        "design_status": "Not Started",
        "qa_status": "Not Started",
        "priority": "Medium",
        "category_tag": "restock",
        "next_deadline": datetime.date(2026, 5, 11),
        "next_deadline_label": "Copy review",
        "task_assignments": [
            {"task": "Review copy draft", "team": "Brand & Social", "role": "Reviewer", "note": "", "due": datetime.date(2026, 5, 11)},
            {"task": "Approve brief", "team": "Marketing Director", "role": "Decision Maker", "note": "", "due": datetime.date(2026, 5, 10)},
        ],
    },
    {
        "id": "MC004",
        "name": "VIP Early Access — Summer Drop",
        "category": "VIP/Loyalty",
        "channel": "email",
        "send_date": datetime.date(2026, 5, 22),
        "phase": "design",
        "tags": ["VIP", "Launch"],
        "segment": "VIP Segment (3+ orders)",
        "audience_est": 8420,
        "subject_line_draft": "You're first — Summer Drop opens early for VIPs",
        "preview_text_draft": "Exclusive 48-hour window. Your early access starts now.",
        "copy_notes": "Tone: exclusive, warm, premium. No discount language. CTA: Shop Early Access.",
        "personalization_notes": "First name + order count badge (e.g. 'As a 4× buyer')",
        "design_brief": "Bold hero image of summer collection. Dark/moody palette. Gold accent CTAs.",
        "revenue_est": 22400,
        "assigned_to": "Sam Torres",
        "brief_status": "Approved",
        "design_status": "In Progress",
        "qa_status": "Not Started",
        "priority": "High",
        "category_tag": "vip",
        "next_deadline": datetime.date(2026, 5, 20),
        "next_deadline_label": "Design approval",
        "task_assignments": [
            {"task": "Design hero image", "team": "Design", "role": "Task Owner", "note": "", "due": datetime.date(2026, 5, 18)},
            {"task": "Approve final design", "team": "Marketing Director", "role": "Decision Maker", "note": "", "due": datetime.date(2026, 5, 20)},
        ],
    },
    {
        "id": "MC005",
        "name": "Flash Sale: 20% Off Hoops",
        "category": "Promotional",
        "channel": "sms",
        "send_date": datetime.date(2026, 5, 3),
        "phase": "execution",
        "tags": ["Flash Sale", "Discount"],
        "segment": "All SMS — Engaged 90d",
        "audience_est": 21800,
        "subject_line_draft": "",
        "preview_text_draft": "",
        "copy_notes": "GLINTA: 20% off all hoops today only. Code HOOPS20. Shop: [link]",
        "personalization_notes": "No personalization — broadcast message",
        "design_brief": "SMS only — no design required",
        "revenue_est": 9600,
        "assigned_to": "Jordan Park",
        "brief_status": "Approved",
        "design_status": "Approved",
        "qa_status": "In Progress",
        "priority": "High",
        "category_tag": "promo",
        "next_deadline": datetime.date(2026, 5, 3),
        "next_deadline_label": "QA sign-off",
        "task_assignments": [
            {"task": "QA test send", "team": "Growth Marketing", "role": "Task Owner", "note": "", "due": datetime.date(2026, 5, 3)},
        ],
    },
    {
        "id": "MC006",
        "name": "Studio Opening — Williamsburg",
        "category": "Studio/Retail",
        "channel": "email",
        "send_date": datetime.date(2026, 5, 30),
        "phase": "planning",
        "tags": ["Studio", "Event"],
        "segment": "NYC Metro Subscribers",
        "audience_est": 11200,
        "subject_line_draft": "",
        "preview_text_draft": "",
        "copy_notes": "",
        "personalization_notes": "City-level personalization — 'Your Williamsburg studio is open'",
        "design_brief": "",
        "revenue_est": 7400,
        "assigned_to": "Maya Chen",
        "brief_status": "Not Started",
        "design_status": "Not Started",
        "qa_status": "Not Started",
        "priority": "Medium",
        "category_tag": "studio",
        "next_deadline": datetime.date(2026, 5, 23),
        "next_deadline_label": "Brief due",
        "task_assignments": [],
    },
    {
        "id": "MC007",
        "name": "Graduation Gift Guide",
        "category": "Editorial",
        "channel": "email",
        "send_date": datetime.date(2026, 5, 17),
        "phase": "decisioning",
        "tags": ["Editorial", "Gift"],
        "segment": "All Email Subscribers",
        "audience_est": 52340,
        "subject_line_draft": "",
        "preview_text_draft": "",
        "copy_notes": "",
        "personalization_notes": "Price-range filtering based on LTV — show higher-AOV picks to top spenders",
        "design_brief": "",
        "revenue_est": 14700,
        "assigned_to": "Sam Torres",
        "brief_status": "Not Started",
        "design_status": "Not Started",
        "qa_status": "Not Started",
        "priority": "Medium",
        "category_tag": "editorial",
        "next_deadline": datetime.date(2026, 5, 10),
        "next_deadline_label": "Audience sign-off",
        "task_assignments": [
            {"task": "Pull graduation audience segment", "team": "Data", "role": "Input Provider", "note": "", "due": datetime.date(2026, 5, 10)},
        ],
    },
    {
        "id": "MC008",
        "name": "Back in Stock: Diamond Flatbacks",
        "category": "Restock",
        "channel": "sms",
        "send_date": datetime.date(2026, 5, 8),
        "phase": "generation",
        "tags": ["Restock", "Urgency"],
        "segment": "Diamond Wishlist + Engaged",
        "audience_est": 9340,
        "subject_line_draft": "",
        "preview_text_draft": "",
        "copy_notes": "Draft: 'GLINTA: Diamond flatbacks are back. You were on the wishlist — shop before they sell out: [link]'",
        "personalization_notes": "Wishlist trigger — only send to subscribers who saved this SKU",
        "design_brief": "SMS only — no design required",
        "revenue_est": 8100,
        "assigned_to": "Jordan Park",
        "brief_status": "Draft",
        "design_status": "Not Started",
        "qa_status": "Not Started",
        "priority": "High",
        "category_tag": "restock",
        "next_deadline": datetime.date(2026, 5, 7),
        "next_deadline_label": "Copy approval",
        "task_assignments": [
            {"task": "Review SMS copy", "team": "Brand & Social", "role": "Reviewer", "note": "", "due": datetime.date(2026, 5, 7)},
        ],
    },
]

PHASES = ["planning", "decisioning", "generation", "design", "execution"]

PHASE_LABELS = {
    "planning":    "Planning",
    "decisioning": "Decisioning",
    "generation":  "Generation",
    "design":      "Design",
    "execution":   "Execution",
}


def get_campaign_by_id(campaign_id):
    return next((c for c in MOCK_CAMPAIGNS if c["id"] == campaign_id), MOCK_CAMPAIGNS[0])


def get_campaign_by_name(name):
    return next((c for c in MOCK_CAMPAIGNS if c["name"] == name), MOCK_CAMPAIGNS[0])


def campaigns_in_phase(phase):
    return [c for c in MOCK_CAMPAIGNS if c["phase"] == phase]


def campaign_names():
    return [c["name"] for c in MOCK_CAMPAIGNS]


def campaign_selector_index(session_key="active_campaign_id"):
    import streamlit as st
    active_id = st.session_state.get(session_key, MOCK_CAMPAIGNS[0]["id"])
    ids = [c["id"] for c in MOCK_CAMPAIGNS]
    return ids.index(active_id) if active_id in ids else 0
